name: CI

on:
  push:
  schedule:
    - cron: '0 0 * * 1' # Every monday at midnight

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: unlink bats
      run: |
        # need to unlink original bats to use bats core
        brew unlink bats
      if: matrix.os == 'macOS-latest'
    - name: install bats-core
      run: |
        brew install --force bats-core
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install python packages
      run: |
        poetry install
    - name: Test
      run: |
        # bats -r does not follow symlinks, pass paths explicitly using find
        bats $(find ./tests -name '*.bats' | sort)
