name: CI

on:
  push:
  schedule:
    - cron: '0 0 * * 1' # Every monday at midnight

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Install bats
      run: |
        git clone https://github.com/bats-core/bats-core
        bash ./bats-core/install.sh /usr/local
    - name: install cookiecutter
      run: |
        pip install cookiecutter
    - name: Test
      run: |
        # bats -r does not follow symlinks, pass paths explicitly using find
        bats $(find ./tests -name '*.bats' | sort)
